[package]
name = "rustft8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"wav_io" = "0.1"
"rustfft" = "6"
"realfft" = "3"
"libm" = "0.2.2"
"plotters" = "0.3.2"